package control

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/joho/godotenv"
	"github.com/kuldeep-poonia/Incident-Response-agent/internal/observability/topology"
)

type RCAAnalysis struct {
	IncidentType       string   `json:"incident_type"`
	SuspectedRootCause string   `json:"suspected_root_cause"`
	AffectedServices   []string `json:"affected_services"`
	Confidence         float64  `json:"confidence"`
	Explanation        string   `json:"explanation"`
}

// RCAService is the extracted Root Cause Agent.
// It actively observes the current EKF physics state and topology bottleneck
// to provide LLM-assisted diagnosis WITHOUT interfering with mathematical mitigation.
type RCAService struct {
	ModelName string
}

func NewRCAService() *RCAService {
	return &RCAService{
		ModelName: "DeepSeek-V3", // Standard GitHub Models alias
	}
}

// AnalyzeActiveIncident queries the AI model with the current live state during an incident.
func (rs *RCAService) AnalyzeActiveIncident(
	criticalPath topology.CriticalPath, 
	currentState *SystemState, 
	serviceID string,
) (RCAAnalysis, error) {
	_ = godotenv.Load() // Ignore error, rely on env if already set
	
	githubToken := os.Getenv("GITHUB_TOKEN")
	if githubToken == "" {
		return RCAAnalysis{}, fmt.Errorf("GITHUB_TOKEN not found in environment")
	}

	prompt := fmt.Sprintf(`You are an elite Site Reliability Engineer AI diagnosing an ACTIVE incident.
Your job is to identify the root cause of the current instability.

--- CURRENT EKF SYSTEM STATE (%s) ---
Failure Mode: %s
Queue Depth: %.2f
Latency: %.4fs (SLA: %.4fs)
Retry Pressure: %.2f
Capacity Velocity: %.2f
Risk Score: %.2f

--- TOPOLOGY BOTTLENECK ---
Nodes in Critical Path: %v
Path Congestion Weight: %.2f
Cascade Risk: %.2f

Based on the telemetry above, return a JSON object with EXACTLY these keys:
{
  "incident_type": "string (e.g., Cascade, Downstream Timeout, Capacity Exhaustion)",
  "suspected_root_cause": "string (1 sentence description of what is failing)",
  "affected_services": ["list", "of", "strings"],
  "confidence": float (0.0 to 1.0),
  "explanation": "string (brief justification based on metrics)"
}`, serviceID, currentState.FailureMode, currentState.QueueDepth, currentState.Latency, currentState.SLATarget,
		currentState.RetryPressure, currentState.CapacityVelocity, currentState.Risk, 
		criticalPath.Nodes, criticalPath.TotalWeight, criticalPath.CascadeRisk)

	type ChatMessage struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	}

	reqBody := struct {
		Model       string        `json:"model"`
		Messages    []ChatMessage `json:"messages"`
		Temperature float64       `json:"temperature"`
		MaxTokens   int           `json:"max_tokens"`
	}{
		Model: rs.ModelName,
		Messages: []ChatMessage{
			{Role: "system", Content: "You are an SRE agent. Output ONLY valid JSON, no markdown blocks."},
			{Role: "user", Content: prompt},
		},
		Temperature: 0.1,
		MaxTokens:   500,
	}

	jsonData, _ := json.Marshal(reqBody)
	req, _ := http.NewRequest("POST", "https://models.inference.ai.azure.com/chat/completions", bytes.NewBuffer(jsonData))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+githubToken)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return RCAAnalysis{}, fmt.Errorf("API request failed: %w", err)
	}
	defer resp.Body.Close()

	bodyBytes, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return RCAAnalysis{}, fmt.Errorf("API returned status %d", resp.StatusCode)
	}

	var chatResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	
	if err := json.Unmarshal(bodyBytes, &chatResp); err != nil {
		return RCAAnalysis{}, fmt.Errorf("failed to parse AI response wrapper: %w", err)
	}

	if len(chatResp.Choices) == 0 {
		return RCAAnalysis{}, fmt.Errorf("no response generated by AI")
	}

	rawContent := chatResp.Choices[0].Message.Content
	rawContent = strings.TrimPrefix(rawContent, "```json")
	rawContent = strings.TrimPrefix(rawContent, "```")
	rawContent = strings.TrimSuffix(rawContent, "```")
	rawContent = strings.TrimSpace(rawContent)

	var analysis RCAAnalysis
	if err := json.Unmarshal([]byte(rawContent), &analysis); err != nil {
		// Fallback for LLM formatting errors
		analysis.IncidentType = currentState.FailureMode
		analysis.SuspectedRootCause = "LLM Parsing Failed"
		analysis.Explanation = "LLM returned invalid JSON: " + rawContent
	}
	
	return analysis, nil
}
